### ISSUE TITLE
Provide pure-floss build flavor

### ISSUE THREAD

**Issue by pizzamaker** [tribeirom/FoodRestrictions#2]
Play Services is non-free software, could you provide a gradle flavor that does not require this?

This is needed for inclusion on F-Droid

**Comment by tribeirom** [comment]
pizzamaker. it's removed! :D. Could you please, check it?

**Comment by pizzamaker** [comment]
@tribeirom Thanks! Please let krt know in https://f-droid.org/forums/topic/food-restriction/

**Comment by krt16s** [comment]
Ref: https://gitlab.com/fdroid/rfp/issues/47
